# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2c918651f3ddf8654140f624707da636bfbfed342285ef1e19d5fc81b10cd6644515c1ee8191ec83c12e2bef662c0c842cd2c46cad87a057711c536d66d28be

test:
  secret_key_base: 86c04c1675a980433e50dc8e67e0b8aabbe138cff7d95145cc7ba6b87c7fcdaef880894efd4d15ed802f69580bb0700d70ec16d4f46c9f764e32687da4d3b43b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
